theme = "onedark"

[editor]
line-number = "relative"
mouse = false
cursorline = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "file-type", "position-percentage", "position", "file-encoding"]

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert.j]
k = "normal_mode"

[keys.normal]
j = "move_char_left"
k = "move_line_down"
l = "move_line_up"
";" = "move_char_right"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

[keys.normal.g]
j = "goto_line_start"
";" = "goto_line_end"

[keys.select]
j = "extend_char_left"
k = "extend_line_down"
l = "extend_line_up"
";" = "extend_char_right"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
